branches:
  only:
    - master

language: php

php: 
  - 5.4
  - 5.5

before_script:
  - git submodule update
  - echo "<?php return \"production\";" > bootstrap/env.php
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
