safe: true
port: 4001
baseurl: /
url: http://orchestral.github.io/orchestraplatform.com/
exclude: ['init.sh', 'README.md', 'docs/README.md']

name: "Orchestra Platform"
description: "Provide a solid base off of which to build your new web applications. It's not a CMS. Instead, it's a springboard to build off of with many of the tools you wish you had on projects but never took the time to build."
latest_version: 2.0.5

markdown: rdiscount
pygments: true
permalink: pretty
paginate: 10
paginate_path: '/blogs/page-:num'
